name: CI/CD FastAPI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: vege503/hello-app:latest

    - name: Checkout manifests repository
      uses: actions/checkout@v3
      with:
        repository: lucas44993/hello-manifests
        token: ${{ secrets.PAT }}
        path: ./manifests

    - name: Update image tag in manifests
      run: |
        cd ./manifests
        sed -i 's|image: vege503/hello-app[:@].*|image: vege503/hello-app:latest|g' deployment.yaml
        if ! git diff --quiet --exit-code deployment.yaml; then
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add deployment.yaml
          git commit -m "Update hello-app image to latest"
          git push
        else
          echo "No changes detected in deployment.yaml. Image tag is already set to latest."
        fi
      shell: /usr/bin/bash -e {0}