name: CI/CD FastAPI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: vege503/hello-app:latest

    - name: Checkout manifests repository
      uses: actions/checkout@v3
      with:
        repository: lucas44993/hello-manifests
        token: ${{ secrets.PAT }}
        path: ./manifests

    - name: Configure Git for Pull Request
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Update image tag in deployment.yaml
      id: update_manifest
      run: |
        cd ./manifests
        sed -i 's|image: vege503/hello-app[:@].*|image: vege503/hello-app:latest|g' deployment.yaml
        
        if ! git diff --quiet --exit-code deployment.yaml; then
          echo "changes_detected=true" >> $GITHUB_OUTPUT # Sintaxe atualizada
          echo "Changes detected in deployment.yaml. Ready to create Pull Request."
        else
          echo "changes_detected=false" >> $GITHUB_OUTPUT # Sintaxe atualizada
          echo "No changes detected in deployment.yaml. Skipping Pull Request."
        fi

    - name: Create Pull Request
      if: steps.update_manifest.outputs.changes_detected == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        commit-message: "chore(app): Update hello-app image to latest"
        title: "Atualização da Imagem hello-app para latest"
        body: |
          Este Pull Request atualiza a tag da imagem `hello-app` para `latest` no `deployment.yaml`.
          Disparado por push no repositório da aplicação.
        branch: "update-image-tag-${{ github.sha }}"
        base: "main"
        delete-branch: true
        directory: ./manifests